ERROR - 2023-03-15 01:51:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:51:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:53:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:53:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:55:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:55:35 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:57:03 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:57:03 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:57:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:57:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:57:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:57:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:58:14 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:58:14 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 01:58:57 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'qlbaocao' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'qlbaocao', 3306, '', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'qlbaocao' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\Codeigniter4\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#7 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-15 01:58:57 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'qlbaocao'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:09:01 --> Allowed fields must be specified for model: "App\Models\UserModel"
in SYSTEMPATH\BaseModel.php on line 1242.
 1 SYSTEMPATH\BaseModel.php(1242): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\UserModel')
 2 SYSTEMPATH\BaseModel.php(919): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 4 SYSTEMPATH\BaseModel.php(690): CodeIgniter\Model->update('admin1', Object(App\Entities\UserEntity))
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:19:25 --> Cannot use object of type App\Entities\UserEntity as array
in APPPATH\Views\dashboard\user.php on line 91.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 4 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 5 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:21:54 --> Object of class App\Entities\UserEntity could not be converted to string
in APPPATH\Views\dashboard\user.php on line 89.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 4 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 5 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:22:11 --> Array to string conversion
in APPPATH\Views\dashboard\user.php on line 89.
 1 APPPATH\Views\dashboard\user.php(89): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'APPPATH\\Views\\dashboard\\user.php', 89)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\dashboard\\user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 5 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 6 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:26:35 --> Allowed fields must be specified for model: "App\Models\UserModel"
in SYSTEMPATH\BaseModel.php on line 1242.
 1 SYSTEMPATH\BaseModel.php(1242): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\UserModel')
 2 SYSTEMPATH\BaseModel.php(757): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:32:55 --> Allowed fields must be specified for model: "App\Models\UserModel"
in SYSTEMPATH\BaseModel.php on line 1242.
 1 SYSTEMPATH\BaseModel.php(1242): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\UserModel')
 2 SYSTEMPATH\BaseModel.php(757): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:33:59 --> Attempt to read property "user_id" on array
in APPPATH\Views\dashboard\user.php on line 91.
 1 APPPATH\Views\dashboard\user.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_id" on array', 'APPPATH\\Views\\dashboard\\user.php', 91)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\dashboard\\user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 5 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 6 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:34:26 --> in_array(): Argument #2 ($haystack) must be of type array, string given
in SYSTEMPATH\BaseModel.php on line 1246.
 1 SYSTEMPATH\BaseModel.php(1246): in_array('user_id', 'App\\Entities\\UserEntity', true)
 2 SYSTEMPATH\BaseModel.php(757): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:35:15 --> in_array(): Argument #2 ($haystack) must be of type array, string given
in SYSTEMPATH\BaseModel.php on line 1246.
 1 SYSTEMPATH\BaseModel.php(1246): in_array('user_id', 'App\\Entities\\UserEntity', true)
 2 SYSTEMPATH\BaseModel.php(757): CodeIgniter\BaseModel->doProtectFields([...])
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 4 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:42:47 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 02:42:47 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `user_status`, `group_id`, `user`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :user_status:, :group_id:, :user:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:51:48 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 02:51:48 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `user_status`, `group_id`, `user`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :user_status:, :group_id:, :user:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 02:51:57 --> Attempt to read property "user_id" on array
in APPPATH\Views\dashboard\user.php on line 91.
 1 APPPATH\Views\dashboard\user.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "user_id" on array', 'APPPATH\\Views\\dashboard\\user.php', 91)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\dashboard\\user.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 5 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 6 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:52:20 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 02:52:20 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`, `user`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:, :user:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:55:29 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 02:55:29 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`, `user`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:, :user:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:56:07 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Array)
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 02:56:07 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`, `user`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:, :user:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 02:57:16 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `users` ...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(690): CodeIgniter\Model->update('admin1', Array)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Array)
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 02:57:16 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `user_id` = :user_id:, `username` = :username:, `password` = :password:, `email` = :email:, `phonenumber` = :phonenumber:, `gender` = :gender:, `user_status` = :user_status:, `group_id` = :group_id:, `user` = :user:
WHERE `users`.`user_id` IN :users.user_id:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(690): CodeIgniter\Model->update('admin1', [...])
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:18:53 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `users` ...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(690): CodeIgniter\Model->update('admin1', Array)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Array)
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 03:18:53 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `user_id` = :user_id:, `username` = :username:, `password` = :password:, `email` = :email:, `phonenumber` = :phonenumber:, `gender` = :gender:, `group_id` = :group_id:, `user` = :user:
WHERE `users`.`user_id` IN :users.user_id:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(690): CodeIgniter\Model->update('admin1', [...])
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:19:27 --> mysqli_sql_exception: Unknown column 'user' in 'field list' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `users` ...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(690): CodeIgniter\Model->update('admin1', Array)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Array)
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 03:19:27 --> Unknown column 'user' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `users` SET `user_id` = :user_id:, `username` = :username:, `password` = :password:, `email` = :email:, `phonenumber` = :phonenumber:, `gender` = :gender:, `group_id` = :group_id:, `user` = :user:
WHERE `users`.`user_id` IN :users.user_id:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 SYSTEMPATH\BaseModel.php(690): CodeIgniter\Model->update('admin1', [...])
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:19:42 --> mysqli_sql_exception: Duplicate entry '' for key 'PRIMARY' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Array)
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 03:19:42 --> Duplicate entry '' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:21:48 --> mysqli_sql_exception: Duplicate entry '' for key 'PRIMARY' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(692): CodeIgniter\Model->insert(Object(App\Entities\UserEntity), false)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Object(App\Entities\UserEntity))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 03:21:48 --> Duplicate entry '' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert(Object(App\Entities\UserEntity), false)
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Object(App\Entities\UserEntity))
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-03-15 03:21:53 --> Cannot use object of type App\Entities\UserEntity as array
in APPPATH\Views\dashboard\user.php on line 91.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('dashboard/user', [], true)
 4 APPPATH\Controllers\BaseController.php(62): view('dashboard/user', [...])
 5 APPPATH\Controllers\Dashboard\User.php(31): App\Controllers\BaseController->page_construct('dashboard/user', [...], [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:23:24 --> mysqli_sql_exception: Duplicate entry '' for key 'PRIMARY' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(692): CodeIgniter\Model->insert(Object(App\Entities\UserEntity), false)
#8 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Object(App\Entities\UserEntity))
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#11 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#13 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#14 {main}
CRITICAL - 2023-03-15 03:23:24 --> Duplicate entry '' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert(Object(App\Entities\UserEntity), false)
 6 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\BaseModel->save(Object(App\Entities\UserEntity))
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:24:07 --> mysqli_sql_exception: Duplicate entry '' for key 'PRIMARY' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 03:24:07 --> Duplicate entry '' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `group_id`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :group_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-15 03:37:33 --> mysqli_sql_exception: Duplicate entry 'admin1' for key 'PRIMARY' in D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 D:\Xampp\htdocs\Codeigniter4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\Xampp\htdocs\Codeigniter4\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\Xampp\htdocs\Codeigniter4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\Xampp\htdocs\Codeigniter4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 D:\Xampp\htdocs\Codeigniter4\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\Xampp\htdocs\Codeigniter4\app\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
#8 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
#9 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
#10 D:\Xampp\htdocs\Codeigniter4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\Codeigniter4\public\index.php(68): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\Codeigniter4\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}
CRITICAL - 2023-03-15 03:37:33 --> Duplicate entry 'admin1' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`user_id`, `username`, `password`, `email`, `phonenumber`, `gender`, `user_status`, `group_id`) VALUES (:user_id:, :username:, :password:, :email:, :phonenumber:, :gender:, :user_status:, :group_id:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Dashboard\User.php(28): CodeIgniter\Model->insert(Object(App\Entities\UserEntity))
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard\User->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard\User))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(68): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
